package com.simpleQuiz.simple.quiz.project.quiz.data.model.js1QuizZ;

import lombok.Getter;

@Getter
    public enum JS1Answers {

        ANSWER1("A default constructor is a constructor in a class that is automatically" +
                " generated by the compiler if no other constructor is explicitly defined in the class."),
        ANSWER2("Can lead to ambiguity issues when a class " +
                        "inherits from multiple classes with conflicting methods or attributes"),
        ANSWER3(" Optimizes memory layout for efficiency."),
        ANSWER4("Use techniques such as proper resource ordering, timeout mechanisms," +
                " and deadlock detection algorithms to prevent and handle deadlocks."),
        ANSWER5("Translates entire program code to machine code before execution," +
                " Executes code line by line without a prior translation to machine code"),
        ANSWER6("Provides a specific implementation for a method in a subclass that is already defined in its superclass," +
                "Involves having multiple methods in the same class with the same name but different parameter lists."),
        ANSWER7("A stream that deals with characters. Reads and writes data character by character," +
                " which is more suitable for handling text-based data."),
        ANSWER8("Software Development Life Cycle (SDLC):\n" +
                "A process for planning, creating, testing, deploying, and maintaining software. Common phases include" +
                " requirements, design, implementation, testing, deployment, and maintenance."),
        ANSWER9("Variable types are determined at compile-time. Type errors are caught during compilation.," +
                "Dynamically Typed:\n" +
                "Variable types are determined at runtime. Type errors are caught during execution.\n" ),
        ANSWER10("Minimizes data duplication.\n" +
                "Reduces update anomalies.\n" +
                "Enhances data consistency and integrity.");

    private String answer;
        JS1Answers(String answer) {
            this.answer = answer;
        }
    }
